services:
  postgres:
    image: postgres:17
    container_name: spendlytics-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: spendlytics
      POSTGRES_USER: ganpat
      POSTGRES_PASSWORD: Job@0508@#

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: